[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
goblin = "0.10"

[[bin]]
name = "abi_generator"
path = "src/bin/abi_generator.rs"

[[bin]]
name = "abi_codegen"
path = "src/bin/abi_codegen.rs"

[[bin]]
name = "avm32"
path = "src/bin/avm32.rs"
